# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
    'require':
      'frameworks/extra-cmake-modules': '@latest-kf6'
      'frameworks/kconfigwidgets': '@latest-kf6'

Options:
  require-passing-tests-on: ['@all']
